
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const FIT_SCREEN = 'FIT_SCREEN';
export const WORKOUT_SCREEN = 'WORKOUT_SCREEN';
export const BOTTOM_TAB = 'BOTTOM_TAB';
export const REST_SCREEN = 'REST_SCREEN';
export const SUBSCRIPTION_SCREEN = 'SUBSCRIPTION_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const ADMIN_SCREEN = 'ADMIN_SCREEN';
export const PROTIEN_SELLING_SCREEN = 'PROTIEN_SELLING_SCREEN';




